### ISSUE TITLE
Error: (0x51b998,0x59acf8) When trying to use Cloudflare R2?

### ISSUE THREAD

**Issue by wovalle** [eeshugerman/postgres-backup-s3#29]
Hi! I'm trying to run this project but I'm getting an error I can't decipher:

```
04/02/2023 6:47:19 PM new cron: @daily
04/02/2023 6:47:19 PM (0x51b998,0x59acf8)
04/02/2023 6:47:19 PM Stopping
04/02/2023 6:47:19 PM Waiting
04/02/2023 6:47:19 PM Exiting
04/02/2023 6:47:20 PM new cron: @daily
```

My docker compose looks like this:

```yaml
version: '3'

services:
  pg:
    container_name: pg
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      PGDATABASE: ${POSTGRES_DB}
    volumes:
       - pg:/data/postgres
    ports:
      - "5432:5432"

  pg_backup:
    image: eeshugerman/postgres-backup-s3:15
    container_name: pg_backup
    environment:
      SCHEDULE: '@daily'    
      BACKUP_KEEP_DAYS: 7    
      PASSPHRASE: ${PG_BACKUP_PASSPHRASE}
      S3_REGION: "" # Empty since is not required in Cloudflare R2
      S3_ACCESS_KEY_ID: ${PG_BACKUP_S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${PG_BACKUP_S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${PG_BACKUP_S3_BUCKET}
      S3_PREFIX: ${PG_BACKUP_S3_PREFIX}
      S3_ENDPOINT: ${PG_BACKUP_S3_ENDPOINT}
      POSTGRES_HOST: pg
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
```

I don't know what's failing or why. Can you point me in the right direction?
