### ISSUE TITLE
Not working with Linode

### ISSUE THREAD

**Issue by antarr** [eeshugerman/postgres-backup-s3#63]
I'm trying to use Linode Object Store as the backup server. I'm getting any errors when running. But nothing is created either. I'm using Kamal+Docker. The current configuration using AWS does work.

### deploy.yml
```
  s3_backup:
    image: eeshugerman/postgres-backup-s3:16
    roles:
      - web
    env:
      clear:
        SCHEDULE: '@daily'
        BACKUP_KEEP_DAYS: 30
        POSTGRES_HOST: *host
        POSTGRES_DATABASE: production_user_data
        POSTGRES_USER: <POSTGRES_USER>
        S3_REGION: us-southeast-1
        S3_PREFIX: production_backups
        S3_BUCKET: wevote-daily-pg-backups
        S3_ENDPOINT: https://mybucket.us-southeast-1.linodeobjects.com
        S3_ACCESS_KEY_ID: <LINODE_ACCESS_KEY>
        S3_SECRET_ACCESS_KEY: <LINODE_SECRET>
      secret:
        - POSTGRES_PASSWORD
```
